"""add user relationship to accounts

Revision ID: 4d8afc9903b3
Revises: b762f3b2e16f
Create Date: 2026-08-06 19:22:23.098760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d8afc9903b3'
down_revision: Union[str, Sequence[str], None] = 'b762f3b2e16f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('accounts_name_key'), 'accounts', type_='unique')
    op.create_unique_constraint('uq_user_account_name', 'accounts', ['user_id', 'name'])
    op.create_foreign_key(None, 'accounts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_constraint('uq_user_account_name', 'accounts', type_='unique')
    op.create_unique_constraint(op.f('accounts_name_key'), 'accounts', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('accounts', 'user_id')
    # ### end Alembic commands ###
