"""add transaction type

Revision ID: 878c9c52880c
Revises: 2789bba72069
Create Date: 2026-08-24 23:32:11.795883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878c9c52880c'
down_revision: Union[str, Sequence[str], None] = '2789bba72069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "transactions",
        sa.Column(
            "transaction_type",
            sa.String(length=50),
            nullable=True
        )
    )

    op.execute(
        """
        UPDATE transactions
        SET transaction_type = 'LOAN_RECEIVED'
        WHERE transaction_type IS NULL
        """
    )

    op.alter_column(
        "transactions",
        "transaction_type",
        nullable=False
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transaction_type')
    # ### end Alembic commands ###
